Repository juanpernu/BilogWeb, pull requests merged in 2021-02, with the labels that each got.

#49 Adjust component for the new layout (BILW-027)
  components/Feature/Feature.js
  mocks/featureTest.js
  mocks/general.js
  mocks/odontologicaMock.js
  pages/feature.js
  pages/odontologica.js
Labels: squash and merge

#53 Add gtm for chile
  components/Layout.js
  config/index.js
Labels: enhancement

#58 fix: change http to https urls
  mocks/general.js
  next.config.js
Labels: bug

#50 Feature/bilw 038
  components/Docs/Docs.js
  components/Docs/DocsWrapper.js
  components/Docs/Item.js
  components/Docs/Sidebar.js
  components/Docs/content.js
Labels: enhancement

#61 Creacion del archivo que contiene la estructura JSON con la data que corresponde a BilogApp.js
  components/Carousel.js
  mocks/landingMock.js
  pages/bilogApp.js
Labels: enhancement

#43 Creacion del newswletter bilog-app (BILW-028)
  static/emails/bilog-app.html
Labels: enhancement

#59 Added an arrow that indicates "scroll down" (BILW-033)
  components/Cover/Cover.js
  mocks/landingMock.js
  pages/bilogApp.js
  static/arrow-scroll-down.svg
Labels: squash and merge

#62 Changed the icons of Customer Area (BILW-040)
  components/CardUser/CardUser.js
  components/CardUser/CardUserList.js
  components/Icons/Contact.js
  components/Icons/Documentation.js
  components/Icons/Faqs.js
  components/Icons/Icons.js
  components/Icons/Testimonials.js
  mocks/cardUserData.js
  static/card-user-1.png
  static/card-user-2.png
  static/card-user-3.png
  static/card-user-4.png
Labels: squash and merge

#64 Apply new landing design
  components/Buttons/StoreButtons.js
  components/Cover/Cover.js
  components/Icons/Alarm.js
  components/Icons/Icons.js
  components/Icons/Info.js
  components/Icons/Support.js
  components/Image.js
  components/Menu/Desktop.js
  components/Menu/Mobile.js
  mocks/general.js
  mocks/landingMock.js
  next.config.js
  pages/auditoria.js
  pages/bilogApp.js
  pages/index.js
  pages/laboratorio.js
  pages/odontologica.js
  pages/users.js
  pages/utils.js
  static/landing-nativa/arrow-left.png
  static/landing-nativa/arrow-right.png
  static/landing-nativa/icon-1.png
  static/landing-nativa/icon-2.png
  static/landing-nativa/icon-3.png
  static/landing-nativa/icon-4.png
  static/landing-nativa/icon-5.png
  static/landing-nativa/icon-6.png
  static/landing-nativa/illustration.png
  static/landing-nativa/mobile-1.png
  static/landing-nativa/mobile-2.png
  static/landing-nativa/mobile-3.png
  static/landing-nativa/plus-icon.png
Labels: enhancement

#67 Newsletter informativo de Bilog App (BILW-043)
  static/emails/bilog-lanzamiento-tres.html
Labels: enhancement

#65 Newsletter dedicado al lanzamiento de la App de Bilog. (BILW-042)
  static/emails/bilog-lanzamiento-dos.html
Labels: enhancement

#69 Modifications in the support section of the footer (BILW-047)
  mocks/general.js
Labels: enhancement

#70 New icons in user center and style settings (BILW-048)
  components/CardUser/CardUser.js
  components/Title.js
  mocks/cardUserData.js
  static/bilog-contact.svg
  static/bilog-documentation.svg
  static/bilog-faqs.svg
  static/bilog-testimony.svg
Labels: enhancement
