Repository juanpernu/BilogWeb, pull requests merged in 2021-01, with the labels that each got.

#16 Nueva sección "Usuarios"
  README.md
  components/Menu/Desktop.js
  components/Menu/Mobile.js
  next.config.js
  pages/users.js
Labels: enhancement

#28 Create an accordion component that reads data from the JSON and renders it (BILW-009)
  components/Faq/FAQ.js
  components/Faq/index.js
  pages/faqs.js
Labels: enhancement, squash and merge

#27 Creacion de la estructura JSON
  mocks/docs.js
Labels: enhancement, squash and merge

#25 Se creo sub-sección/vista "Documentación"
  next.config.js
  pages/document.js
Labels: enhancement

#30 FAQs section History
  components/Faq/FAQ.js
  components/Faq/index.js
  mocks/faqs.js
  next.config.js
  pages/faqs.js
Labels: enhancement, squash and merge

#31 fix: remove contact and change wording
  components/Menu/Desktop.js
  components/Menu/Mobile.js
  pages/customer-area.js
Labels: enhancement

#40 Create documentation content and view
  components/Docs/Docs.js
  components/Docs/DocsWrapper.js
  components/Docs/Item.js
  components/Docs/Sidebar.js
  components/Docs/content.js
  contents/documentation/content.js
  contents/documentation/sidebar.js
  contexts/docContext.js
  mocks/cardUserData.js
  next.config.js
Labels: enhancement, squash and merge

#41 Create documentation content and view (#40)
  components/Docs/Docs.js
  components/Docs/DocsWrapper.js
  components/Docs/Item.js
  components/Docs/Sidebar.js
  components/Docs/content.js
  contents/documentation/content.js
  contents/documentation/sidebar.js
  contexts/docContext.js
  mocks/cardUserData.js
  next.config.js
Labels: enhancement

#42 Create encuesta mailing
  static/emails/bilog-encuesta.html
Labels: enhancement

#44 Created a component Badge that consumes the JSON and allows to display the different testimonials (BILW-017)
  components/Testimonials/Badge.js
  components/Testimonials/index.js
  mocks/cardUserData.js
  mocks/testimonials.js
  pages/testimonials.js
Labels: enhancement, squash and merge

#46 fix: workaround to match hash in docs
  components/Docs/Sidebar.js
  components/Docs/SidebarSection.js
  contents/documentation/sidebar.js
Labels: bug
